### PR TITLE
Localize android messages

### LINKED ISSUE #323: Localize startup messages on Android

### PR DESCRIPTION
**Pull request by zhuiks**
Fixes #323

### CODE REVIEW

**Comment by tobias-klein** [comment]
I just tested this on my Android 10 tablet and it does not seem to work. I still see the English messages on startup.

**Comment by zhuiks** [comment]
> I just tested this on my Android 10 tablet and it does not seem to work. I still see the English messages on startup. I switched to different languages and restarted a couple of times, but the loading messages were not localized.

Which language do you switched to? I've tested on Android Emulator with Ukrainian and Russian, since I am able to translate into those languages. All other languages are not translated

**Comment by tobias-klein** [comment]
Uh, that must be it. Duh! Let me check again with translated German locales.

**Comment by tobias-klein** [comment]
I just tested with the Russian and Ukrainian locale and those work!

**Review by tobias-klein — APPROVED** [review]

**Pull request merged**
