### PR TITLE
Fix startup on Librem Phone

### PR DESCRIPTION
**Pull request by programmin1**
I fixed startup on Librem 5 and I was able to get it more workable on its small screen.
Now this works for Librem Phone :)
It could be better and could have some rules to make it workable on the wide landscape orientation too...

### CODE REVIEW

**Comment by tobias-klein** [comment]
@programmin1 Thank you very much for your contribution! Good job :). That's a good start!
I just checked this via the small screen emulation and what I get is visible in the screenshot below. This is without showing tags/notes indicators and without showing the book/chapter navigation.
ezra_bible_app_portrait_600px_with_tags


Here is some feedback regarding the UI:
* I think we could afford to still add some more horizontal space between the buttons in the menu, it looks quite crammed.
* When no tags/notes indicators are shown we should remove the padding on the left side of the verse references. In that case it would still be ok to have the verse references on the same line as the verse text - it looks a bit odd right now.
* In order to work without book/chapter navigation we should ideally have links to the previous/next chapter in the beginning and end of the text. This can be handled separately via #647.

Regarding the technical side:
* How about moving the styles for the phone screen to a separate CSS file (add it in index.html)
* Are the dependency updates all necessary? I understand the update for sqlite3, but not for all the other packages that were uplifted.
* You initially struggled with the build a bit. Is there anything you would add to the build instruction (see BUILD.md) to make it easier for other developers who try something similar in the future?

**Comment by programmin1** [comment]
I thought I replied to this earlier but here goes:

I changed the spacing a little bit but if it's too big it goes off the right of the screen.

For the last technical issues:
1) Separated mobile css now along with fixing broken dialog on my phone.
2) It looks like there are important minor releases in each of those.
3) As long as these updated libraries are in it should work with the build instructions.

**Comment by tobias-klein** [comment]
> I thought I replied to this earlier but here goes:
> 
> I changed the spacing a little bit but if it's too big it goes off the right of the screen.
> 
> For the last technical issues:
> 
> 1. Separated mobile css now along with fixing broken dialog on my phone.
> 2. It looks like there are important minor releases in each of those.
> 3. As long as these updated libraries are in it should work with the build instructions.

Thanks for the updates!

Now currently these are only adjustments to make the build possible. However, what would be needed to provide a package on Librem phone? I suppose it would need to be a Debian package?

If you can come up with a Docker image that contains a complete build toolchain then that could be used to automatically generate packages each time the build is running on GitHub actions.

We could also handle this in a separate issue/pull request, though. The Docker images for building and packaging Ezra Bible App for different Linux distributions are kept here:
https://github.com/ezra-bible-app/ezra-bible-app-docker

**Comment by programmin1** [comment]
> Now currently these are only adjustments to make the build possible. However, what would be needed to provide a package on Librem phone? I suppose it would need to be a Debian package?

Yes, I just open a .deb to install an app. It should have
```
X-Purism-FormFactor=Workstation;Mobile;
```
[in the .desktop file](https://howtotrainyourrobot.com/building-a-linux-app-part-7-building-installer-file/) to be able to be seen on phones without hitting the show non phone apps filter.

> If you can come up with a Docker image that contains a complete build toolchain then that could be used to automatically generate packages each time the build is running on GitHub actions.

Not sure how you do that but if you just build for Ubuntu or any other Debian, **ARM64** arch it should make a .deb that should run on most or all Linux phones.

**Comment by tobias-klein** [comment]
Thank you @programmin1! I have just squash-merged this after making some coding style fixes in mobile.css. GitHub does not detect that this was merged, so I am closing the PR now.

**Comment by tobias-klein** [comment]
> > Now currently these are only adjustments to make the build possible. However, what would be needed to provide a package on Librem phone? I suppose it would need to be a Debian package?
> 
> Yes, I just open a .deb to install an app. It should have
> 
> ```
> X-Purism-FormFactor=Workstation;Mobile;
> ```
> 
> [in the .desktop file](https://howtotrainyourrobot.com/building-a-linux-app-part-7-building-installer-file/) to be able to be seen on phones without hitting the show non phone apps filter.
> 
> > If you can come up with a Docker image that contains a complete build toolchain then that could be used to automatically generate packages each time the build is running on GitHub actions.
> 
> Not sure how you do that but if you just build for Ubuntu or any other Debian, **ARM64** arch it should make a .deb that should run on most or all Linux phones.

@programmin1 
Feel free to contribute this - I'll be glad to support. I have no possibility to test this on my end.

**Pull request closed without merging**
