### PR TITLE
Tag groups

### LINKED ISSUE #599: Select complete existing filter text when clicking into tag list filter input field

### LINKED ISSUE #648: Tab title is getting too long when selecting many tags
image

### LINKED ISSUE #649: File name of exported file is getting too long when selecting many tags

### LINKED ISSUE #650: Chapter navigation / Highlight chapters that contain tagged verses
In order to quickly see which portions of a book's text are tagged, the chapter navigation bar shall highlight the chapters that contain tagged verses.

### PR DESCRIPTION
**Pull request by tobias-klein**
See discussion #540.

* [x] List tag groups
* [x] Add tag group
* [x] Validate tag group title in add dialog
* [x] Validate tag group title in rename dialog
* [x] Delete tag group
* [ ] Delete tag group recursively (including tags)
* [x] Rename tag group
* [x] Create tags within tag group
* [x] Assign existing tags to current tag group
* [x] Hide link "Add existing tags to current group" if all existing tags have been added
* [x] Remove tag from current tag group
* [x] Assign additional tag groups to a tag
* [x] Show visual feedback when tag group is assigned to existing tag
* [x] Remove tag groups from a tag
* [x] Show filtered tag list - based on tag group
* [x] Tagged verses selection - Filter function based on tag groups
* [x] Bible text - filter tags based on currently opened tag group
* [x] Bible text - hide tag indicators if no tags are left when applying the filter
* [x] Bible text - re-apply tag group filter when assigning tags to a verse
* [x] Use loading indicator in tag list, also when tag group is selected
* [x] Fix #648
* [x] Fix #649
* [x] Fix #650
* [x] Fix #599
* [x] Update locales
* [x] Optimize tag group UI related styles on Android
* [x] Add tag-group related acceptance tests
* [x] Add API documentation for new tag-group related classes/components

### CODE REVIEW

**Comment by tobias-klein** [comment]
@debritto
Would you like to provide early user feedback?
Current builds are available [here](https://github.com/ezra-bible-app/ezra-bible-app/actions/runs/1977504317).

Note that I haven't considered the tag groups in the Bible browser or export functions yet. What you can provide feedback on is the UI in the tag list, which now allows to browse tags based on tag groups and perform all necessary edit operations on tag groups.

**Comment by tobias-klein** [comment]
@debritto 
The [latest build](https://github.com/ezra-bible-app/ezra-bible-app/actions/runs/2008275731) has a few bugfixes related to the tag group management and also features a new option to filter the tags shown in the Bible text - based on the currently selected tag group (see new option in options menu).

**Comment by tobias-klein** [comment]
@zhuiks
This is a fairly big PR, but it only makes sense in one piece :)
Would you like to look over it? Any feedback before I merge?

@debritto
Any testing feedback on this PR before I merge?
The latest build is [here](https://github.com/ezra-bible-app/ezra-bible-app/actions/runs/2143152854).

**Review by augustin-colesnic — APPROVED** [review]

**Comment by zhuiks** [comment]
> @zhuiks This is a fairly big PR, but it only makes sense in one piece :) Would you like to look over it? Any feedback before I merge?

Sorry, I don't think I'll have time for at least couple more month.

**Comment by tobias-klein** [comment]
Ok! Thanks for the feedback!

**Pull request merged**
