### PR TITLE
Make dictionary window responsive

### LINKED ISSUE #240: Responsive dictionary window
I think the dictionary window should be a bit more responsive for smaller window sizes:
Знімок екрану з 2021-04-29 16-22-29

### PR DESCRIPTION
**Pull request by zhuiks**
Closes #240 

The main change was to have tags/dictionary window height in percent. Currently, if dictionary window is shown it splits in 60%/40% proportion

### CODE REVIEW

**Comment by zhuiks** [comment]
@tobias-klein few questions:
- Can you explain the comment `FIXME` for the [`resizeAppContainer`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/app/frontend/helpers/ui_helper.js#L125) What needs to be done?
- I coudn't find any use of `#tags-content-book` except in [`toolbox.css`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/css/toolbox.css#L191) Is it just legacy code?

**Comment by tobias-klein** [comment]
> * Can you explain the comment `FIXME` for the [`resizeAppContainer`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/app/frontend/helpers/ui_helper.js#L125) What needs to be done?

At the end of `resizeAppContainer` you have a for loop that iterates through the open tabs and calls `resizeVerseList`. Technically this would only have to be done for the current tab, but the question is where this function then needs to be called additionally to ensure that the `resizeVerseList` call is properly happening. In any case the question is whether this has a performance impact at all ... to be measured and checked!

> * I coudn't find any use of `#tags-content-book` except in [`toolbox.css`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/css/toolbox.css#L191) Is it just legacy code?

That's legacy code and could be removed. In a previous version before the Desktop/Electron app there used to be book-specific tags and this was visually separated in the UI. That feature has been removed for simplification.

**Comment by tobias-klein** [comment]
Thanks for this! It's nice that we can get rid of some JavaScript and replace it with a pure CSS solution!

**Review by tobias-klein — DISMISSED** [review]

**Comment by zhuiks** [comment]
> > * Can you explain the comment `FIXME` for the [`resizeAppContainer`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/app/frontend/helpers/ui_helper.js#L125) What needs to be done?
> 
> At the end of `resizeAppContainer` you have a for loop that iterates through the open tabs and calls `resizeVerseList`. Technically this would only have to be done for the current tab, but the question is where this function then needs to be called additionally to ensure that the `resizeVerseList` call is properly happening. In any case the question is whether this has a performance impact at all ... to be measured and checked!

I looked at `resizeVerseList` and I think it can be refactored in pure css. But I leave that for another issue.

 
> > * I coudn't find any use of `#tags-content-book` except in [`toolbox.css`](https://github.com/ezra-bible-app/ezra-bible-app/blob/8e4f1b9668efe914d2f4a1fd26bc71d3ad3307b8/css/toolbox.css#L191) Is it just legacy code?
> 
> That's legacy code and could be removed. In a previous version before the Desktop/Electron app there used to be book-specific tags and this was visually separated in the UI. That feature has been removed for simplification.

I removed that mention

**Comment by tobias-klein** [comment]
Thanks, this looks good. I would opt for a 50/50 ratio by default.

**Review by tobias-klein — APPROVED** [review]

**Pull request merged**
