### PR TITLE
Update Ukrainian and russian localization

### PR DESCRIPTION
**Pull request by zhuiks**

### CODE REVIEW

**Comment by zhuiks** [comment]
Resolves #770 for Ukrainian and russian

**Comment by tobias-klein** [comment]
Thank you very much, @zhuiks! I am glad to see these two locales updated! :)

**Comment by zhuiks** [comment]
You are very welcome!
Please tag me before the next release.

**Comment by tobias-klein** [comment]
Ok, I will! :)

**Pull request merged**
