### PR TITLE
Pre-load section headers and allow navigation to sections from other chapters

### LINKED ISSUE #340: Chapter navigation: Load section headers for complete book upfront
A pre-condition is to fix the latest SWORD trunk issues on Windows, so that the new section header loading function is available there, too.

### PR DESCRIPTION
**Pull request by tobias-klein**
This fixes #340.

For testing you need to set the book loading mode to "Open all books chapter-wise".

There are updates in `package.json` so you need to run `npm install`.

### CODE REVIEW

**Comment by tobias-klein** [comment]
Hi @zhuiks

Would you mind testing and reviewing this PR?

**Review by zhuiks — DISMISSED** [review]
Very nice! 
All the code looks good, although I didn't dig in into logic much.

I noticed two inconsistencies when switching translations:
1. Switching translation doesn't always update navigation headers. And it seems to be "stacked" in a certain version (switching to RusSynodal and then back to NASB):
Screenshot from 2022-02-09 19-00-03

2. When I turn on "heading navigation" while in translation without headers (Ukrainian) and then switch to translation with headers (NASB), navigation headers remain blank:
Screenshot from 2022-02-09 18-48-25

Let me know if you can't reproduce these issues. I'll dig into it more

**Comment by tobias-klein** [comment]
@zhuiks Thanks for testing this! I applied some fixes for the issues you observed. Would you mind testing once more?

**Comment by zhuiks** [comment]
I'm still getting empty headers in navigation in the following (quite unlikely) use case:
1. Turn nav-headers off in any translation;
2. Switch to the translation with headers;
3. Turn nav-headers on.

**Result:** Blank headers in nav (similar to the second screenshot earlier).

**Comment by tobias-klein** [comment]
> I'm still getting empty headers in navigation in the following (quite unlikely) use case:
> 
> 1. Turn nav-headers off in any translation;
> 2. Switch to the translation with headers;
> 3. Turn nav-headers on.
> 
> **Result:** Blank headers in nav (similar to the second screenshot earlier).

Thanks for reporting this! I will fix this before merging.

**Pull request merged**
