### PR TITLE
Si slovenian translation

### PR DESCRIPTION
**Pull request by msavli**

### CODE REVIEW

**Comment by tobias-klein** [comment]
Hi @msavli!

This PR shows an old set of commits (from November) that have already been merged to the master branch. It does not contain changes for the latest translation updates.

I would suggest to create a new branch from latest master and do the translation there.
Let me know if you need support there - feel free to contact me via email.

**Comment by msavli** [comment]
You should consider using some other app for translators. This is too much
for me. I am not a developer.

I made all necessary translation changes, and now these changes disappeared.

Again I am in front of maountain  "How to make pull request?"

And there were also other words to translate, you didn't mention.
Same could be with other translations.

It is better to remove me from this slovenian translators list. I made
almost 2 "waste hours."


       ------------   Marjan   ----------
        e-mail: ***@***.***
       --------------------------------------


V V pon., 8. jan. 2024 ob 08:45 je oseba Tobias Klein <
***@***.***> napisala:

**Comment by msavli** [comment]
From clipboard I manage to recreate file.
Maybe there could be still some issue with " characters.
If it fits, then ok.

And please remove me from this list.
It is too difficult to me. :-)

       ------------   Marjan   ----------
        e-mail: ***@***.***
       --------------------------------------


V V pon., 8. jan. 2024 ob 09:00 je oseba Marjan Šavli <
***@***.***> napisala:

**Comment by tobias-klein** [comment]
@msavli I am sorry this did not work out for you. I just sent you an email with some further options.

**Pull request closed without merging**
