### PR TITLE
Android toolbar layout fix

### LINKED ISSUE #337: Android: Showing toolbar results in invalid / buggy layout
This was observed on Android. When switching on the tool bar, I got this as a result ... and this feels like a regression (I don't think this is a bug in any release).

Screenshot_2021-06-06-11-50-05-253~2

### PR DESCRIPTION
**Pull request by zhuiks**
fixes #337

### CODE REVIEW

**Comment by tobias-klein** [comment]
Mmmm... I tested this just now and I couldn't reproduce the bug anymore. However, after switching back to master I also couldn't reproduce the bug anymore. The thing is that technically the dictionary can't even be turned on with Android (the option is hidden).

**Comment by tobias-klein** [comment]
I actually reproduced this again (it happens once you have opened the drop down tag list at least once) and the fix helps (to some extent). What's missing is that the vertical height of the tag list is "endless" instead of adjusted to the window height. I think this is handled in UiHelper.resizeAppContainer. I may have another look later this week and see whether I can fix this. 

image

**Comment by zhuiks** [comment]
> I actually reproduced this again (it happens once you have opened the drop down tag list at least once) and the fix helps (to some extent). What's missing is that the vertical height of the tag list is "endless" instead of adjusted to the window height. I think this is handled in UiHelper.resizeAppContainer. I may have another look later this week and see whether I can fix this.

Can we put this on hold for now. I really want to finish #302 which refactor the whole layout without representing new features. My goal to adjust resizing in pure CSS without utilizing JavaScript (`UiHelper.resizeAppContainer`)

**Comment by tobias-klein** [comment]
> Can we put this on hold for now. I really want to finish #302 which refactor the whole layout without representing new features. My goal to adjust resizing in pure CSS without utilizing JavaScript (`UiHelper.resizeAppContainer`)

Sure. Then let's prioritize #302 for 1.2.

**Comment by tobias-klein** [comment]
@zhuiks Feel free to close this if you think everything is addressed in #302.

**Comment by zhuiks** [comment]
Everything addressed in #302

**Pull request closed without merging**
