### PR TITLE
Add integrated online help that gives an overview for all keyboard shortcuts

### PR DESCRIPTION
**Pull request by augustin-colesnic**
Covering #198

### CODE REVIEW

**Comment by tobias-klein** [comment]
Thank you for this contribution!

One general feedback: What's the idea behind putting the actual shortcuts into the locale? The shortcuts themselves are not different per language, are they? How about putting in the special keys like shift, ctrl, etc. but not the full short cut? Then we can assemble the translations dynamically in the template.

Visually I would suggest to align the column header text left.

**Comment by augustin-colesnic** [comment]
> One general feedback: What's the idea behind putting the actual shortcuts into the locale? The shortcuts themselves are not different per language, are they? How about putting in the special keys like shift, ctrl, etc. but not the full short cut? Then we can assemble the translations dynamically in the template. That would also allow us to add additional shortcuts in the future without having to translate them each time.


**I was wondering the same until I noticed there is on shortcut with explanation on it** (more than the shortcut itself) that states: Shift + mouse over verse while dictionary info is opened. If we get rid of that we could also remove the shortcut section from translation indeed. :)

**Comment by augustin-colesnic** [comment]
So, @tobias-klein what about this long description in the shortcutcolumn for the SHIFT + mouse over? 
Here are the latest changes:
keboward shortcuts Ezra Bible App - 27 may 2021

**Comment by augustin-colesnic** [comment]
Romanian translation for keyboard shortcuts  

romanian translation for keyboard shortcuts

**Comment by tobias-klein** [comment]
The one for "shift plus mouse over" is the only exception, right? So in that case I don't have a problem with a specific entry that needs to be localized, but in all the other cases we can build the shortcut from two independently localized parts, right?

**Comment by tobias-klein** [comment]
Here is another feedback on the visual presentation ...

I think the content is quite easy to read and we do not necessarily need the column headers. However, we could use the left column to insert a "header" whenever a new group of functionality starts ... maybe currently:
1. Font size
2. Current tab search
3. Miscellaneous

There will likely be more shortcuts in the future, so I think we should put them in functionality groups.

**Comment by tobias-klein** [comment]
@augustin-colesnic Any additional feedback on this?

**Comment by augustin-colesnic** [comment]
> Here is another feedback on the visual presentation ...
> 
> I think the content is quite easy to read and we do not necessarily need the column headers. However, we could use the left column to insert a "header" whenever a new group of functionality starts ... maybe currently:
> 
> 1. Font size
> 2. Current tab search
> 3. Miscellaneous
> 
> There will likely be more shortcuts in the future, so I think we should put them in functionality groups.

Oh yes @tobias-klein  those are good observations and I will implement them right away. Sorry for the late replay. I was off the radar lately :smile:

**Comment by augustin-colesnic** [comment]
> The one for "shift plus mouse over" is the only exception, right? So in that case I don't have a problem with a specific entry that needs to be localized, but in all the other cases we can build the shortcut from two independently localized parts, right?

Right now there are 2 independently localised parts (column1 and column2). Do you want me to have only the first column translated and leave the second one without the possibility to be localised?

**Comment by augustin-colesnic** [comment]
Latest changes:

Screenshot 2021-06-11 at 20 55 10

**Comment by tobias-klein** [comment]
I'll look in detail later during the weekend! On the road today.

How about some padding between the shortcut groups? At least 0.5 or 1em?

**Comment by tobias-klein** [comment]
> Right now there are 2 independently localised parts (column1 and column2). Do you want me to have only the first column translated and leave the second one without the possibility to be localised?

**Regarding the second column:**

What I intend here is that we translate the actual keyboard keys (CMD / CTRL / SHIFT) ... because there are translations (CTRL for example is STRG in German). But then the letter/character after that does not need a translation, because it is fixed. So with that said, you can have the "control keys" in the locale, and combine them with a fixed letter (not in locale) inside the code. Does that make sense?

This way we can keep the locale a bit leaner and minimize update effort in the future.

**Comment by augustin-colesnic** [comment]
> > Right now there are 2 independently localised parts (column1 and column2). Do you want me to have only the first column translated and leave the second one without the possibility to be localised?
> 
> **Regarding the second column:**
> 
> What I intend here is that we translate the actual keyboard keys (CMD / CTRL / SHIFT) ... because there are translations (CTRL for example is STRG in German). But then the letter/character after that does not need a translation, because it is fixed. So with that said, you can have the "control keys" in the locale, and combine them with a fixed letter (not in locale) inside the code. Does that make sense?
> 
> This way we can keep the locale a bit leaner and minimize update effort in the future.

Nope it does not make sense for me! :flushed: I would say let us leave it locale also for the second column (shortcut one) and if needed to translate (like german) it will be or if it is not needed it will not be. Simpler that way!

**Comment by augustin-colesnic** [comment]
Added the padding (top and bottom) to the section titles

Screenshot 2021-06-12 at 14 24 18

**Comment by tobias-klein** [comment]
> > > Right now there are 2 independently localised parts (column1 and column2). Do you want me to have only the first column translated and leave the second one without the possibility to be localised?
> > 
> > 
> > **Regarding the second column:**
> > What I intend here is that we translate the actual keyboard keys (CMD / CTRL / SHIFT) ... because there are translations (CTRL for example is STRG in German). But then the letter/character after that does not need a translation, because it is fixed. So with that said, you can have the "control keys" in the locale, and combine them with a fixed letter (not in locale) inside the code. Does that make sense?
> > This way we can keep the locale a bit leaner and minimize update effort in the future.
> 
> Nope it does not make sense for me! 😳 I would say let us leave it locale also for the second column (shortcut one) and if needed to translate (like german) it will be or if it is not needed it will not be. Simpler that way!

OK. 👍

**Comment by tobias-klein** [comment]
The only thing I still need to test is how it looks in portrait mode on a 7" tablet. I think you increased the width of the dialog a bit. We may need to make it responsive to screen size. You can also test this my simply resizing the window to a width of 600px or so.

**Comment by tobias-klein** [comment]
Did you add the new keys/texts to all existing locale files? If not, please do.

**Comment by augustin-colesnic** [comment]
> Did you add the new keys/texts to all existing locale files? If not, please do.

No I did not add those to other locale except (EN) and (RO).  
I see the other locale defaults to (EN), please see below screenshot.
1. Shouldn't each translator add those to its own locale? 
2. If you want me to add them,  shall i add the english one to other locale?

Note: I need to increase the with of the window so the tabs should fit in for other locale like French and Spanish:

Screenshot 2021-06-12 at 15 30 38

**Comment by augustin-colesnic** [comment]
Done. @tobias-klein  please review me last 2 commits

**Comment by tobias-klein** [comment]
Yes, we add the English ones to all other locales. This is then becoming a todo for translators. In the future we should add a script that syncs missing entries to all other languages based on the English one. Whenever I ask translators I give them the exact keys. This way it's most convenient for them I think.

**Comment by augustin-colesnic** [comment]
@tobias-klein  what's pending on this one? Can we merge this?

**Comment by tobias-klein** [comment]
Yes. Sorry, I was simply busy with other things on the weekend. The only thing I need to check is whether this is responsive on different tablet screen sizes.

**Comment by tobias-klein** [comment]
@augustin-colesnic Thanks once more! I did a few more optimizations and just merged!

**Pull request merged**
