### PR TITLE
Add packaging support for Fedora 37 (fixes #819)

### LINKED ISSUE #819: Packaging support for Fedora 37
I've just tried installing Ezra on a new Fedora 37 system and getting the following errors:
```
$ sudo dnf install ./ezra-bible-app_fedora35-1.8.0.rpm 
Last metadata expiration check: 0:06:29 ago on Wed 23 Nov 2022 07:37:00 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libicu69 needed by ezra-bible-app-1.8.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

$ rpm -i ezra-bible-app_fedora35-1.8.0.rpm 
error: Failed dependencies:
	libicu69 is needed by ezra-bible-app-1.8.0-1.x86_64
	sqlite is needed by ezra-bible-app-1.8.0-1.x86_64
```

The libicu libraries are now newer than what Ezra expects:
```
$ rpm -q libicu
libicu-71.1-2.fc37.x86_64

$ rpm -ql libicu | grep lib64
/usr/lib64/libicudata.so.71
/usr/lib64/libicudata.so.71.1
/usr/lib64/libicui18n.so.71
/usr/lib64/libicui18n.so.71.1
/usr/lib64/libicuio.so.71
/usr/lib64/libicuio.so.71.1
/usr/lib64/libicutest.so.71
/usr/lib64/libicutest.so.71.1
/usr/lib64/libicutu.so.71
/usr/lib64/libicutu.so.71.1
/usr/lib64/libicuuc.so.71
/usr/lib64/libicuuc.so.71.1
```
Could you please take a look at this when the next version gets built? Thank you so much!

### PR DESCRIPTION
**Pull request by tobias-klein**

### CODE REVIEW

**Comment by tobias-klein** [comment]
Build currently failing, a fix may first be needed in node-sword-interface.

**Comment by tobias-klein** [comment]
@magicsysrq
I added the needed changes to generate the Fedora 37 package.
Would you like to give this a try?
I added you as contributor with Read permissions, which should give you access to the GitHub action's builds.
You find a generated Fedora 37 package [here](https://github.com/ezra-bible-app/ezra-bible-app/suites/9495098596/artifacts/450296569).
Would you mind installing it and providing feedback?

**Comment by magicsysrq** [comment]
Thank you so much for your help with this.
Unfortunately, the package installation still fails with dependency complaints:

```
$ sudo dnf install ./ezra-bible-app_latest.rpm 
Last metadata expiration check: 0:52:48 ago on Thu 24 Nov 2022 11:09:59 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libicu71 needed by ezra-bible-app-1.9.0.Dev-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
The package in F37 is called simply `libicu`, so I think you can safely drop the version number from the requirement and that should do the trick. Earlier releases had the version in the package name but not any more.
All these libraries are installed on my system:
```
$ sudo ldconfig -p | grep libicu
	libicuuc.so.71 (libc6,x86-64) => /lib64/libicuuc.so.71
	libicutu.so.71 (libc6,x86-64) => /lib64/libicutu.so.71
	libicutest.so.71 (libc6,x86-64) => /lib64/libicutest.so.71
	libicui18n.so.71 (libc6,x86-64) => /lib64/libicui18n.so.71
	libicuio.so.71 (libc6,x86-64) => /lib64/libicuio.so.71
	libicudata.so.71 (libc6,x86-64) => /lib64/libicudata.so.71
```

**Comment by tobias-klein** [comment]
@magicsysrq 
Thanks for your feedback!
I corrected the dependency with 30cdce1b818102c3b8afd8b8f44a38ff9277ff82.
Here is [a new build](https://github.com/ezra-bible-app/ezra-bible-app/suites/9500131248/artifacts/450694108).
Would you mind testing once more.

**Comment by magicsysrq** [comment]
Yes, this package has installed without any issues. I definitely appreciate the limited text column width in this version also. Thank you!

**Comment by tobias-klein** [comment]
Thanks @magicsysrq! Just merged this to `master`.

**Pull request merged**
