### PR TITLE
Add Romanian emoji annotations

### PR DESCRIPTION
**Pull request by zhuiks**
For desktop/electron app emoji annotations still needed to be generated/added manually in case of new app locale. That had not been done for Romanian locale. This PR solves that.

@augustin-colesnic can you verify that you are able to see Romanian emoji annotations and able to search for emoji in Romanian
Screenshot from 2021-06-21 20-16-44

Please make sure to update emoji-button package from my github repository: 
```
npm update github:zhuiks/emoji-button
```
After this the file `node_modules/emoji-button/dist/locale/emoji_ro.json` should be present

### CODE REVIEW

**Comment by tobias-klein** [comment]
> For desktop/electron app emoji annotations still needed to be generated/added manually in case of new app locale.

@zhuiks I think this extra step is not mentioned in the translation how-to in the contribution guidelines. Would you mind adding it there?

**Comment by augustin-colesnic** [comment]
@zhuiks  I tried.
following your steps but i stil do not see the Romanian locale there.

I even tried with npm update **github:zhuiks/emoji-button** and **npm update github:zhuiks/emoji-button#master** as i noticed the package is named in dependencies.

Screenshot 2021-06-22 at 09 06 36

Please advise further.

**Comment by zhuiks** [comment]
@augustin-colesnic sorry, please try
```
npm install github:zhuiks/emoji-button
```
If that would not trigger the update, try
```
rm  node_modules/emoji-button/ -rf
npm cache clean --force
npm install github:zhuiks/emoji-button
```

**Comment by zhuiks** [comment]
> > For desktop/electron app emoji annotations still needed to be generated/added manually in case of new app locale.
> 
> @zhuiks I think this extra step is not mentioned in the translation how-to in the contribution guidelines. Would you mind adding it there?

@tobias-klein 
I'll publish emoji annotations for all CDLR languages under zhuiks/emoji-button. It's just a building time on my computer. Then I think we need to require those annotations dynamically. There was an [issue with browserify](https://github.com/ezra-bible-app/ezra-bible-app/pull/226#issuecomment-830739907) but right now I understand the building process better for Cordova and we don't need those annotations for Cordova anyway. So the file with dynamic emoji annotations can be skipped in browserify build

**Comment by tobias-klein** [comment]
> @augustin-colesnic sorry, please try
> 
> ```
> npm install github:zhuiks/emoji-button
> ```
> 
> If that would not trigger the update, try
> 
> ```
> rm  node_modules/emoji-button/ -rf
> npm cache clean --force
> npm install github:zhuiks/emoji-button
> ```

@augustin-colesnic Would you mind taking another look based on the hints above, so that we can merge this before Saturday?

**Comment by augustin-colesnic** [comment]
> npm install github:zhuiks/emoji-button

I am o in now...

**Review by augustin-colesnic — APPROVED** [review]
Most of the emoji are ok. Anyway there are a ton of them and i can never go through them all. I noticed ones that are not even translated like **judge**  which should be **Judecator**... But the emphasis is on the most common ones.. So I guess we are ok with them.

**Pull request merged**
