### PR TITLE
Implement search scope for module search function

### LINKED ISSUE #518: Add search scope option for module search function

### PR DESCRIPTION
**Pull request by tobias-klein**
This adds a search scope parameter to the module search function and will fix #518.

Currently that parameter has the following options:

* Whole Bible
* Old Testament
* New Testament

### CODE REVIEW

**Comment by tobias-klein** [comment]
@augustin-colesnic @zhuiks 
Any feedback regarding the list of potential search scopes?

Should I also add the following more special ones?
* Gospels
* Pentateuch

Anything else?

Note that I am currently not planning to add a custom scope selection where you can pick the books. This is to keep it simple for now. We could still add that later if really needed.

**Comment by zhuiks** [comment]
How about these:
- Old Testament: Pentateuch
- Old Testament: Historical books
- Old Testament: Poetic books
- Old Testament: Prophets
- New Testament: Historical books (Gospel + Acts)
- New Testament: Epistles
- New Testament: Prophesy (Revelation)

**Comment by tobias-klein** [comment]
> How about these:
> 
> * Old Testament: Pentateuch
> * Old Testament: Historical books
> * Old Testament: Poetic books
> * Old Testament: Prophets
> * New Testament: Historical books (Gospel + Acts)
> * New Testament: Epistles
> * New Testament: Prophesy (Revelation)

Thank you @zhuiks. That's a good list and this is familiar from various Bible outlines.

Having the group "Gospel + Acts" is fine, however - I would personally also want to add the Gospels by themselves. We could do both groups.

**Comment by augustin-colesnic** [comment]
> * Whole Bible
> * Old Testament
> * New Testament

Hi guys, I would not go too granular about this filter. These 3 options are just enough. Otherwise we might end up having a second serch for the filter itself :)

**Comment by tobias-klein** [comment]
Ok, I am going to merge this for now and we can modify the implementation once additional issues are raised and agreed upon.

**Pull request merged**
